### ISSUE TITLE
stanford-english-corenlp-2018-10-05-models.jar

### ISSUE THREAD

**Issue by huyankun2020022098** [thunlp/HMEAE#13]
C:\Anaconda3\envs\tensorflow\python.exe F:/HMEAE-master/train.py --mode DMCNN
WARNING:tensorflow:From F:/HMEAE-master/train.py:26: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

--File Extraction Finish--
--Entity Extraction Finish--
Traceback (most recent call last):
  File "F:/HMEAE-master/train.py", line 26, in <module>
    tf.app.run()
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "F:/HMEAE-master/train.py", line 15, in main
    extractor.Extract()
  File "F:\HMEAE-master\utils.py", line 388, in Extract
    self.Event_Extract()
  File "F:\HMEAE-master\utils.py", line 144, in Event_Extract
    nlp = StanfordCoreNLPv2(constant.corenlp_path)
  File "F:\HMEAE-master\utils.py", line 438, in __init__
    super(StanfordCoreNLPv2,self).__init__(path)
  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\stanfordcorenlp\corenlp.py", line 46, in __init__
    if not subprocess.call(['java', '-version'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT) == 0:
  File "C:\Anaconda3\envs\tensorflow\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Anaconda3\envs\tensorflow\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\envs\tensorflow\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by huyankun2020022098** [comment]
ImportError: Could not find 'cudart64_90.dll'.

**Comment by huyankun2020022098** [comment]
加微信15623266882



---Original---
From: "Xiaozhi ***@***.***&gt;
Date: Fri, Apr 22, 2022 17:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [thunlp/HMEAE] stanford-english-corenlp-2018-10-05-models.jar(Issue #13)




 
Closed #13.
